First commit
ilyukha99/Lab2Net pull request #1
Opened 2020-10-02 18:04 UTC by ilyukha99

@Aloomenon

2020-10-03 15:12 UTC, Aloomenon requested changes
Расскажите, почему вы решили использовать статические методы.

2020-10-04 04:43 UTC, ilyukha99 commented
> Расскажите, почему вы решили использовать статические методы.

Здравствуйте.
В данном случае я отдал предпочтение преимущественно статическому контексту, так как не увидел надобности в создании объектов (исключение - класс ClientRoutine).
Это связано с тем, что мне по большому счёту не приходится проводить какие-то множественные манипуляции над объектами классов, преобразуя их.
Да, я изменяю внутренние состояния статических классов (к примеру, лист с открытыми сокетами клиентов), но не вижу нужды в создании ассоциированных с ними объектов.

2020-10-05 03:32 UTC, Aloomenon commented
Ну ок, принимаю. Имя и фамилию скажите.

2020-10-05 04:54 UTC, ilyukha99 commented
> Ну ок, принимаю. Имя и фамилию скажите.
Илья Шевяков

2020-10-06 03:35 UTC, ilyukha99 commented
> 
> 
> Ну ок, принимаю. Имя и фамилию скажите.

ping

2020-10-06 05:22 UTC, merged